=== GEO-IASS/hyperWavelets/quantizer.dtd
<!ELEMENT quantizer (band+)>
<!ATTLIST quantizer level CDATA "1">
<!ELEMENT band (subband+)>
<!ATTLIST band num CDATA #REQUIRED>
<!ATTLIST band name CDATA #IMPLIED>
<!ELEMENT subband (#PCDATA)>
<!ATTLIST subband num CDATA #REQUIRED>
<!ATTLIST subband width CDATA "1">
<!ATTLIST subband height CDATA "1">
<!ATTLIST subband type CDATA "int">
<!ATTLIST subband shape CDATA "square">
<!ATTLIST subband scale CDATA "1">

=== GEO-IASS/hyperWavelets/quantizer2.xml
<?xml version="1.0"?>
<!DOCTYPE quantizer SYSTEM "quantizer.dtd">
<quantizer level="3">
  <band num="0" name="Red">
    <subband num="0"/>
    <subband num="1" width="2" height="2" scale="4"/>
    <subband num="2" width="2" height="2" scale="4"/>
    <subband num="3" width="2" height="2" scale="4"/>
    <subband num="4" width="4" height="4" scale="8"/>
    <subband num="5" width="4" height="4" scale="8"/>
    <subband num="6" width="4" height="4" scale="8"/>
    <subband num="7" width="8" height="4" scale="16"/>
    <subband num="8" width="4" height="8" scale="16"/>
    <subband num="9" width="4" height="8" scale="16"/>
  </band>
  <band num="1" name="Green">
    <subband num="0"/>
    <subband num="1" width="2" height="2" scale="4"/>
    <subband num="2" width="2" height="2" scale="4"/>
    <subband num="3" width="2" height="2" scale="4"/>
    <subband num="4" width="4" height="4" scale="8"/>
    <subband num="5" width="4" height="4" scale="8"/>
    <subband num="6" width="4" height="4" scale="8"/>
    <subband num="7" width="8" height="4" scale="16"/>
    <subband num="8" width="4" height="8" scale="16"/>
    <subband num="9" width="4" height="8" scale="16"/>
  </band>
  <!-- la banda del azul es menos importante para nuestro ojo ... -->
  <band num="2" name="Blue">
    <subband num="0"/>
    <subband num="1" width="4" height="2" scale="4"/>
    <subband num="2" width="2" height="4" scale="4"/>
    <subband num="3" width="4" height="4" scale="4"/>
    <subband num="4" width="4" height="4" scale="8"/>
    <subband num="5" width="4" height="4" scale="8"/>
    <subband num="6" width="4" height="4" scale="8"/>
    <subband num="7" width="8" height="4" scale="16"/>
    <subband num="8" width="4" height="8" scale="16"/>
    <subband num="9" width="4" height="8" scale="16"/>
  </band>
</quantizer>
